import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navbar from '../components/Navbar'
import HomeCard from '../components/HomeCard'
import HomeContainer from '../components/HomeContainer'

import Stack from '@mui/material/Stack';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogContentText from '@mui/material/DialogContentText';
import DialogTitle from '@mui/material/DialogTitle';
import Typography from '@mui/material/Typography';
import Fab from '@mui/material/Fab';
import DirectionsRunIcon from '@mui/icons-material/DirectionsRun';
import { blue, red } from '@mui/material/colors';


const Home: NextPage = () => {
  const [open, setOpen] = useState(true);

  const handleClose = () => {
    setOpen(false);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>EDU Right - 学生权益维护中心</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar/>
        <Box sx={{maxWidth: 500, margin: '0 auto', p: 2}}>
          <Stack spacing={2}>
            <HomeCard/>
            <HomeContainer/>
          </Stack>
        </Box>
      </main>

      <footer className={styles.footer} >
        <Box sx={{py:6}}></Box>
      </footer>

      <Dialog
        open={open}
        onClose={handleClose}
        aria-labelledby="alert-dialog-title"
        aria-describedby="alert-dialog-description"
      >
        <DialogTitle id="alert-dialog-title">
          使用须知
        </DialogTitle>
        <DialogContent>
          <DialogContentText id="alert-dialog-description">
            <Typography color={blue.A200}>
            本站给出的举报途径均为<strong> “上级”，保密完善，信息泄露风险小 </strong>
              （如老师知道是你举报的，请大胆举报教育局泄露信息）
            </Typography>
            <br />
            <Typography>
              可举报内容比你现象的丰富的多（如作业过量、体罚、收缴私人财产、占课、留学生等等...）
            </Typography>
            <br />
            <Typography color={red.A200}>
              老师只会知道有人举报，但不知道是谁（实测）
            </Typography>
            
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleClose}>
            关闭
          </Button>
        </DialogActions>
      </Dialog>

      <Box>
        <Fab disabled variant="extended" color="success" sx={{position: 'fixed', bottom:'40px', left: '50%',transform: 'translate(-50%, 0)'}}>
          <DirectionsRunIcon sx={{ mr: 1 }} />
          举报引导（未开放）
        </Fab>
      </Box>
    </div>
  )
}

export default Home
